[profile.default]
src = "contracts/src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "Solady/=lib/Solady/src/",
]

[profile.default.fuzz]
runs = 256
